#!/usr/bin/env ansible-playbook

- name: Configure Node Network with Bridges and VLANs
  hosts: controller
  remote_user: root
  sudo: True
  tasks:
  - name: APT Install Packages
    action: apt pkg={{ item }} state=installed
    with_items:
      - qemu-kvm 
      - virt-manager
      - ntp
      - dnsmasq
      - nova-api  
#      - nova-api-metadata  
#      - nova-compute 
#      - nova-compute-qemu 
      - nova-ajax-console-proxy
      - nova-cert
      - nova-conductor
      - nova-doc 
      - novnc 
      - nova-novncproxy 
      - nova-consoleauth
      - nova-scheduler
      - nova-objectstore
      - python-novaclient
      - sasl2-bin
      - build-essential
      - libvirt-bin 
      - pm-utils 
      - sysfsutils

  - name: Configure Neutron DB user
    command: "{{item}}"
    with_items:
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'DROP DATABASE nova;'
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'CREATE DATABASE nova;'
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '{{ MYSQL_NOVA_PASS }}';"
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY '{{ MYSQL_NOVA_PASS }}';"
    ignore_errors: True

  - name: Configure 'libvirtd.conf'
    copy: src=files/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root mode=0644

  - name: Configure 'libvirt.conf'
    copy: src=files/libvirt.conf dest=/etc/libvirt/libvirt.conf owner=root mode=0644

  - name: Configure 'libvirt-bin.conf'
    command: sed -i 's/libvirtd_opts="-d"/libvirtd_opts="-d -l"/g' /etc/default/libvirt-bin

  - name: Configure 'nova.conf'
    template: src=templates/controller/nova.conf.j2 dest=/etc/nova/nova.conf owner=nova group=nova mode=0640

  - name: Nova DB Table Create
    command: su -s /bin/sh -c "nova-manage db sync" nova

  - name: Clean up Nova Log files
    command: su -s /bin/sh -c "for i in `ls /var/log/nova/nova*`; do echo '' > ${i}; done"

  - name: Copy 'clean' script 
    template: src=templates/controller/clean.nova dest=/var/log/nova/clean owner=nova group=root mode=0700

  - name: Restart Nova-related Services
    service: name={{ item }} state=restarted     
    with_items:
    - libvirt-bin
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-cert 
    - nova-consoleauth 
    - nova-novncproxy



