#!/usr/bin/env ansible-playbook

- name: Configure Cinder Serviceon Controller Node
  hosts: controller
  remote_user: root
  sudo: True
  tasks:
  - name: APT Install Packages
    action: apt pkg={{ item }} state=installed
    with_items:
      - cinder-api 
      - cinder-scheduler 
      - python-cinderclient

  - name: Configure Cinder DB user
    command: "{{item}}"
    with_items:
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'DROP DATABASE cinder;'
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'CREATE DATABASE cinder;'
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost' IDENTIFIED BY '{{ MYSQL_NOVA_PASS }}';"
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%' IDENTIFIED BY '{{ MYSQL_NOVA_PASS }}';"
    ignore_errors: True

  - name: Configure 'cinder.conf'
    template: src=templates/storage/cinder.conf.j2 dest=/etc/cinder/cinder.conf owner=cinder group=cinder mode=0640

  - name: Sync Cinder in DB
    shell: cinder-manage db sync

  - name: Copy 'clean' script 
    template: src=templates/storage/clean.cinder dest=/var/log/cinder/clean owner=cinder group=root mode=0700

  - name: Restart Cinder-related Services
    service: name={{ item }} state=restarted     
    with_items:
    - cinder-scheduler
    - cinder-api
