#!/usr/bin/env ansible-playbook

- name: Configure Heat
  hosts: controller
  remote_user: root
  sudo: True
  tasks:
  - name: APT Install Packages
    action: apt pkg={{ item }} state=installed
    with_items:
      - heat-api
      - heat-api-cfn
      - heat-engine
      - python-heatclient

  - name: Configure Heat DB user
    command: "{{item}}"
    with_items:
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'DROP DATABASE heat;'
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'CREATE DATABASE heat;'
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'localhost' IDENTIFIED BY '{{ MYSQL_GLANCE_PASS }}';"
      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'%' IDENTIFIED BY '{{ MYSQL_GLANCE_PASS }}';"
    ignore_errors: True

  - name: Configure 'heat.conf'
    template: src=templates/controller/heat.conf.j2 dest=/etc/heat/heat.conf owner=heat group=root mode=0644

  - name: Heat DB Table Create
    command: heat-manage db_sync

  - name: Restart Heat Services
    service: name={{ item }} state=restarted     
    with_items:
    - heat-api
    - heat-api-cfn
    - heat-engine



        



