#!/usr/bin/env ansible-playbook

- name: Configure Neutron
  hosts: controller-01
  remote_user: root
  sudo: True
  tasks:
#  - name: Install Linux-header
#    command: apt-get -y install linux-headers-`uname -r`

  - name: APT Install Packages
    action: apt pkg={{ item }} state=installed
    with_items:
      - linux-headers-{{ ansible_kernel }}
      - openvswitch-switch
      - openvswitch-datapath-dkms
      - neutron-server 
      - neutron-plugin-ml2 
      - python-neutronclient 
      - ntp

#  - name: Configure Neutron DB user
#    command: "{{item}}"
#    with_items:
#      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'DROP DATABASE neutron;'
#      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e 'CREATE DATABASE neutron;'
#      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ MYSQL_NEUTRON_PASS }}';"
#      - mysql -uroot -p{{ MYSQL_ROOT_PASS }} -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ MYSQL_NEUTRON_PASS }}';"
#    ignore_errors: True

#  - name: restart openvswitch-switch
#    service: name=openvswitch-switch state=restarted 

  - name: Configure 'neutron.conf'
    template: src=templates/controller/neutron.conf.j2 dest=/etc/neutron/neutron.conf owner=neutron group=root mode=0644

  - name: Configure 'ml2_conf.ini'
    template: src=templates/controller/ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner=neutron group=root mode=0644

  - name: Copy 'clean' script 
    template: src=templates/controller/clean.neutron dest=/var/log/neutron/clean owner=neutron group=root mode=0700

#  - name: Neutron DB Table Create
#    command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade juno" neutron

  - name: restart neutron-server
    service: name=neutron-server state=restarted     



