#!/usr/bin/env ansible-playbook

- name: Configure Neutron
  hosts: network
  remote_user: root
  sudo: True
  tasks:

  - name: APT Install Packages
    action: apt pkg={{ item }} state=installed
    with_items:
      - linux-headers-{{ ansible_kernel }}
      - openvswitch-switch
      - python-mysqldb
      - openvswitch-datapath-dkms
      - neutron-server 
      - neutron-plugin-ml2 
      - neutron-plugin-openvswitch-agent 
      - neutron-l3-agent 
      - neutron-lbaas-agent
      - neutron-dhcp-agent
      - python-neutronclient
      - haproxy 
      - ntp

  - name: Configure 'neutron.conf'
    template: src=templates/network/neutron.conf.j2 dest=/etc/neutron/neutron.conf owner=neutron group=root mode=0644

  - name: Configure 'ml2_conf.ini'
    template: src=templates/network/ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner=neutron group=root mode=0644

  - name: Configure 'l3_agent.ini'
    template: src=templates/network/l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini owner=neutron group=root mode=0644

  - name: Configure 'dhcp_agent.ini'
    template: src=templates/network/dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini owner=neutron group=root mode=0644

  - name: Configure 'metadata_agent.ini'
    template: src=templates/network/metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini owner=neutron group=root mode=0644

  - name: Configure 'dnsmasq-neutron.conf '
    template: src=templates/network/dnsmasq-neutron.conf.j2 dest=/etc/neutron/dnsmasq-neutron.conf owner=neutron group=root mode=0644

  - name: Configure 'lbaas_agent.ini'
    template: src=templates/network/lbaas_agent.ini dest=/etc/neutron/lbaas_agent.ini owner=neutron group=root mode=0644

  - name: Configure 'fwaas_driver.ini'
    template: src=templates/network/fwaas_driver.ini dest=/etc/neutron/fwaas_driver.ini owner=neutron group=root mode=0644

  - name: Copy 'clean' script 
    template: src=templates/network/clean.neutron dest=/var/log/neutron/clean owner=neutron group=root mode=0700

  - name: Restart Neutron-related Services
    service: name={{ item }} state=restarted     
    with_items:
      - ntp 
      - openvswitch-switch
      - neutron-plugin-openvswitch-agent 
      - neutron-l3-agent 
      - neutron-dhcp-agent
      - neutron-metadata-agent 
      - neutron-lbaas-agent


