#!/usr/bin/env ansible-playbook
- name: Configure Node Network with Bridges and VLANs
  hosts: compute-02
  remote_user: root
  sudo: True
  tasks:
     - name: Step 1a. APT Install Network Packages
       action: apt pkg={{ item }} state=installed
       with_items:
         - vlan
         - bridge-utils

     - name: Step 1b. Configure Interface File
       template: src=templates/compute/interfaces.j2 dest=/etc/network/interfaces mode=0644

     - name: reboot machine
       command: shutdown -r now "Complete NIC Config"
       async: 0
       poll: 0
       ignore_errors: true


